name: build

on:
  schedule:
    - cron:  '0 0 * * SUN'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: run make build
        run: make
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push generated file
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'SciKGTeX Automatic Builder'
          git config --global user.email 'Christof93@users.noreply.github.com'
          git add scikgtex.lua
          git commit -m "Regenerate ORKG property mapping"
          git push

